#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE auth_server;
    CREATE DATABASE api_server;
    CREATE DATABASE event_server;
    CREATE DATABASE api_server_test;
    CREATE DATABASE api_server_http_test;
    GRANT ALL PRIVILEGES ON DATABASE auth_server TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE api_server TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE event_server TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE api_server_test TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE api_server_http_test TO $POSTGRES_USER;
EOSQL
