#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE auth_server;
    CREATE DATABASE api_server;
    GRANT ALL PRIVILEGES ON DATABASE auth_server TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE api_server TO $POSTGRES_USER;
EOSQL
